import { createFileRoute, Link, useNavigate } from "@tanstack/react-router";
import { useState } from "react";
import { Logo } from "@/components/logo";
import { Button } from "@/components/ui/button";
import { Input } from "@/components/ui/input";
import { supabase } from "@/integrations/supabase/client";
export const Route=createFileRoute("/sign-in")({head:()=>({meta:[{title:"Developer sign in — Splexanode"},{name:"description",content:"Sign in to manage Splexanode applications, widgets, usage, and billing."},{property:"og:title",content:"Developer sign in — Splexanode"},{property:"og:description",content:"Access the Splexanode developer platform."},{property:"og:type",content:"website"},{name:"twitter:card",content:"summary"}]}),component:SignIn});
function SignIn(){const nav=useNavigate();const [email,setEmail]=useState("");const [password,setPassword]=useState("");const [error,setError]=useState("");const [busy,setBusy]=useState(false);async function submit(e:React.FormEvent){e.preventDefault();setBusy(true);const {error}=await supabase.auth.signInWithPassword({email,password});setBusy(false);if(error){setError("Email or password is incorrect.");return}void nav({to:"/home"})}return <AuthShell title="Developer sign in" note="Manage applications, widgets, transfer usage, and billing."><form onSubmit={submit} className="mt-8 space-y-4"><label className="block"><span className="label">Email</span><Input className="mt-2 h-11" type="email" autoComplete="email" value={email} onChange={e=>setEmail(e.target.value)} required/></label><label className="block"><span className="label">Password</span><Input className="mt-2 h-11" type="password" autoComplete="current-password" value={password} onChange={e=>setPassword(e.target.value)} required/></label>{error&&<p className="text-sm text-destructive">{error}</p>}<Button className="h-11 w-full" disabled={busy}>{busy?"Signing in…":"Sign in"}</Button></form><div className="mt-6 flex justify-between text-sm"><Link to="/forgot-password" className="text-muted-foreground hover:text-foreground">Forgot password?</Link><Link to="/sign-up" className="font-medium text-primary">Create account</Link></div></AuthShell>}
export function AuthShell({title,note,children}:{title:string;note:string;children:React.ReactNode}){return <main className="grid min-h-screen lg:grid-cols-[0.85fr_1.15fr]"><aside className="hidden flex-col justify-between bg-ink p-10 text-ink-foreground lg:flex"><Logo className="text-ink-foreground"/><blockquote className="max-w-lg font-display text-4xl font-bold">Infrastructure should disappear behind the transfer.</blockquote><p className="font-mono text-xs text-ink-muted">SPLEXANODE DEV / V1</p></aside><section className="flex items-center justify-center px-5 py-16"><div className="w-full max-w-md"><div className="lg:hidden"><Logo/></div><h1 className="mt-10 text-4xl font-bold lg:mt-0">{title}</h1><p className="mt-3 text-muted-foreground">{note}</p>{children}</div></section></main>}
