/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as AboutRouteImport } from './routes/about'
import { Route as DocsRouteImport } from './routes/docs'
import { Route as ForgotPasswordRouteImport } from './routes/forgot-password'
import { Route as HomeRouteImport } from './routes/home'
import { Route as LogoutRouteImport } from './routes/logout'
import { Route as ProductsRouteImport } from './routes/products'
import { Route as ResetPasswordRouteImport } from './routes/reset-password'
import { Route as ShareRouteImport } from './routes/share'
import { Route as SignInRouteImport } from './routes/sign-in'
import { Route as SignUpRouteImport } from './routes/sign-up'
import { Route as VerifyEmailRouteImport } from './routes/verify-email'
import { Route as AuthenticatedAppsRouteImport } from './routes/_authenticated/apps'
import { Route as AuthenticatedBillingRouteImport } from './routes/_authenticated/billing'
import { Route as AuthenticatedOnboardingRouteImport } from './routes/_authenticated/onboarding'
import { Route as AuthenticatedPlatformRouteImport } from './routes/_authenticated/platform'
import { Route as AuthenticatedPlatformSettingsRouteImport } from './routes/_authenticated/platform-settings'
import { Route as AuthenticatedSettingsRouteImport } from './routes/_authenticated/settings'
import { Route as AuthenticatedUsageRouteImport } from './routes/_authenticated/usage'
import { Route as DocsSlugRouteImport } from './routes/docs/$slug'
import { Route as TTransferIdRouteImport } from './routes/t/$transferId'
import { Route as ToCodeRouteImport } from './routes/to/$code'
import { Route as WidgetWidgetIdRouteImport } from './routes/widget.$widgetId'
import { Route as AuthenticatedAppApplicationIdRouteImport } from './routes/_authenticated/app.$applicationId'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const DocsRoute = DocsRouteImport.update({
  id: '/docs',
  path: '/docs',
  getParentRoute: () => rootRouteImport,
} as any)
const ForgotPasswordRoute = ForgotPasswordRouteImport.update({
  id: '/forgot-password',
  path: '/forgot-password',
  getParentRoute: () => rootRouteImport,
} as any)
const HomeRoute = HomeRouteImport.update({
  id: '/home',
  path: '/home',
  getParentRoute: () => rootRouteImport,
} as any)
const LogoutRoute = LogoutRouteImport.update({
  id: '/logout',
  path: '/logout',
  getParentRoute: () => rootRouteImport,
} as any)
const ProductsRoute = ProductsRouteImport.update({
  id: '/products',
  path: '/products',
  getParentRoute: () => rootRouteImport,
} as any)
const ResetPasswordRoute = ResetPasswordRouteImport.update({
  id: '/reset-password',
  path: '/reset-password',
  getParentRoute: () => rootRouteImport,
} as any)
const ShareRoute = ShareRouteImport.update({
  id: '/share',
  path: '/share',
  getParentRoute: () => rootRouteImport,
} as any)
const SignInRoute = SignInRouteImport.update({
  id: '/sign-in',
  path: '/sign-in',
  getParentRoute: () => rootRouteImport,
} as any)
const SignUpRoute = SignUpRouteImport.update({
  id: '/sign-up',
  path: '/sign-up',
  getParentRoute: () => rootRouteImport,
} as any)
const VerifyEmailRoute = VerifyEmailRouteImport.update({
  id: '/verify-email',
  path: '/verify-email',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedAppsRoute = AuthenticatedAppsRouteImport.update({
  id: '/apps',
  path: '/apps',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedBillingRoute = AuthenticatedBillingRouteImport.update({
  id: '/billing',
  path: '/billing',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedOnboardingRoute = AuthenticatedOnboardingRouteImport.update({
  id: '/onboarding',
  path: '/onboarding',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedPlatformRoute = AuthenticatedPlatformRouteImport.update({
  id: '/platform',
  path: '/platform',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedPlatformSettingsRoute =
  AuthenticatedPlatformSettingsRouteImport.update({
    id: '/platform-settings',
    path: '/platform-settings',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedSettingsRoute = AuthenticatedSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedUsageRoute = AuthenticatedUsageRouteImport.update({
  id: '/usage',
  path: '/usage',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const DocsSlugRoute = DocsSlugRouteImport.update({
  id: '/$slug',
  path: '/$slug',
  getParentRoute: () => DocsRoute,
} as any)
const TTransferIdRoute = TTransferIdRouteImport.update({
  id: '/t/$transferId',
  path: '/t/$transferId',
  getParentRoute: () => rootRouteImport,
} as any)
const ToCodeRoute = ToCodeRouteImport.update({
  id: '/to/$code',
  path: '/to/$code',
  getParentRoute: () => rootRouteImport,
} as any)
const WidgetWidgetIdRoute = WidgetWidgetIdRouteImport.update({
  id: '/widget/$widgetId',
  path: '/widget/$widgetId',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedAppApplicationIdRoute =
  AuthenticatedAppApplicationIdRouteImport.update({
    id: '/app/$applicationId',
    path: '/app/$applicationId',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/docs': typeof DocsRouteWithChildren
  '/forgot-password': typeof ForgotPasswordRoute
  '/home': typeof HomeRoute
  '/logout': typeof LogoutRoute
  '/products': typeof ProductsRoute
  '/reset-password': typeof ResetPasswordRoute
  '/share': typeof ShareRoute
  '/sign-in': typeof SignInRoute
  '/sign-up': typeof SignUpRoute
  '/verify-email': typeof VerifyEmailRoute
  '/apps': typeof AuthenticatedAppsRoute
  '/billing': typeof AuthenticatedBillingRoute
  '/onboarding': typeof AuthenticatedOnboardingRoute
  '/platform': typeof AuthenticatedPlatformRoute
  '/platform-settings': typeof AuthenticatedPlatformSettingsRoute
  '/settings': typeof AuthenticatedSettingsRoute
  '/usage': typeof AuthenticatedUsageRoute
  '/docs/$slug': typeof DocsSlugRoute
  '/t/$transferId': typeof TTransferIdRoute
  '/to/$code': typeof ToCodeRoute
  '/widget/$widgetId': typeof WidgetWidgetIdRoute
  '/app/$applicationId': typeof AuthenticatedAppApplicationIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/docs': typeof DocsRouteWithChildren
  '/forgot-password': typeof ForgotPasswordRoute
  '/home': typeof HomeRoute
  '/logout': typeof LogoutRoute
  '/products': typeof ProductsRoute
  '/reset-password': typeof ResetPasswordRoute
  '/share': typeof ShareRoute
  '/sign-in': typeof SignInRoute
  '/sign-up': typeof SignUpRoute
  '/verify-email': typeof VerifyEmailRoute
  '/apps': typeof AuthenticatedAppsRoute
  '/billing': typeof AuthenticatedBillingRoute
  '/onboarding': typeof AuthenticatedOnboardingRoute
  '/platform': typeof AuthenticatedPlatformRoute
  '/platform-settings': typeof AuthenticatedPlatformSettingsRoute
  '/settings': typeof AuthenticatedSettingsRoute
  '/usage': typeof AuthenticatedUsageRoute
  '/docs/$slug': typeof DocsSlugRoute
  '/t/$transferId': typeof TTransferIdRoute
  '/to/$code': typeof ToCodeRoute
  '/widget/$widgetId': typeof WidgetWidgetIdRoute
  '/app/$applicationId': typeof AuthenticatedAppApplicationIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/about': typeof AboutRoute
  '/docs': typeof DocsRouteWithChildren
  '/forgot-password': typeof ForgotPasswordRoute
  '/home': typeof HomeRoute
  '/logout': typeof LogoutRoute
  '/products': typeof ProductsRoute
  '/reset-password': typeof ResetPasswordRoute
  '/share': typeof ShareRoute
  '/sign-in': typeof SignInRoute
  '/sign-up': typeof SignUpRoute
  '/verify-email': typeof VerifyEmailRoute
  '/_authenticated/apps': typeof AuthenticatedAppsRoute
  '/_authenticated/billing': typeof AuthenticatedBillingRoute
  '/_authenticated/onboarding': typeof AuthenticatedOnboardingRoute
  '/_authenticated/platform': typeof AuthenticatedPlatformRoute
  '/_authenticated/platform-settings': typeof AuthenticatedPlatformSettingsRoute
  '/_authenticated/settings': typeof AuthenticatedSettingsRoute
  '/_authenticated/usage': typeof AuthenticatedUsageRoute
  '/docs/$slug': typeof DocsSlugRoute
  '/t/$transferId': typeof TTransferIdRoute
  '/to/$code': typeof ToCodeRoute
  '/widget/$widgetId': typeof WidgetWidgetIdRoute
  '/_authenticated/app/$applicationId': typeof AuthenticatedAppApplicationIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/docs'
    | '/forgot-password'
    | '/home'
    | '/logout'
    | '/products'
    | '/reset-password'
    | '/share'
    | '/sign-in'
    | '/sign-up'
    | '/verify-email'
    | '/apps'
    | '/billing'
    | '/onboarding'
    | '/platform'
    | '/platform-settings'
    | '/settings'
    | '/usage'
    | '/docs/$slug'
    | '/t/$transferId'
    | '/to/$code'
    | '/widget/$widgetId'
    | '/app/$applicationId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/docs'
    | '/forgot-password'
    | '/home'
    | '/logout'
    | '/products'
    | '/reset-password'
    | '/share'
    | '/sign-in'
    | '/sign-up'
    | '/verify-email'
    | '/apps'
    | '/billing'
    | '/onboarding'
    | '/platform'
    | '/platform-settings'
    | '/settings'
    | '/usage'
    | '/docs/$slug'
    | '/t/$transferId'
    | '/to/$code'
    | '/widget/$widgetId'
    | '/app/$applicationId'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/about'
    | '/docs'
    | '/forgot-password'
    | '/home'
    | '/logout'
    | '/products'
    | '/reset-password'
    | '/share'
    | '/sign-in'
    | '/sign-up'
    | '/verify-email'
    | '/_authenticated/apps'
    | '/_authenticated/billing'
    | '/_authenticated/onboarding'
    | '/_authenticated/platform'
    | '/_authenticated/platform-settings'
    | '/_authenticated/settings'
    | '/_authenticated/usage'
    | '/docs/$slug'
    | '/t/$transferId'
    | '/to/$code'
    | '/widget/$widgetId'
    | '/_authenticated/app/$applicationId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  AboutRoute: typeof AboutRoute
  DocsRoute: typeof DocsRouteWithChildren
  ForgotPasswordRoute: typeof ForgotPasswordRoute
  HomeRoute: typeof HomeRoute
  LogoutRoute: typeof LogoutRoute
  ProductsRoute: typeof ProductsRoute
  ResetPasswordRoute: typeof ResetPasswordRoute
  ShareRoute: typeof ShareRoute
  SignInRoute: typeof SignInRoute
  SignUpRoute: typeof SignUpRoute
  VerifyEmailRoute: typeof VerifyEmailRoute
  TTransferIdRoute: typeof TTransferIdRoute
  ToCodeRoute: typeof ToCodeRoute
  WidgetWidgetIdRoute: typeof WidgetWidgetIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/docs': {
      id: '/docs'
      path: '/docs'
      fullPath: '/docs'
      preLoaderRoute: typeof DocsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/forgot-password': {
      id: '/forgot-password'
      path: '/forgot-password'
      fullPath: '/forgot-password'
      preLoaderRoute: typeof ForgotPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/home': {
      id: '/home'
      path: '/home'
      fullPath: '/home'
      preLoaderRoute: typeof HomeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/logout': {
      id: '/logout'
      path: '/logout'
      fullPath: '/logout'
      preLoaderRoute: typeof LogoutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/products': {
      id: '/products'
      path: '/products'
      fullPath: '/products'
      preLoaderRoute: typeof ProductsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reset-password': {
      id: '/reset-password'
      path: '/reset-password'
      fullPath: '/reset-password'
      preLoaderRoute: typeof ResetPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/share': {
      id: '/share'
      path: '/share'
      fullPath: '/share'
      preLoaderRoute: typeof ShareRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sign-in': {
      id: '/sign-in'
      path: '/sign-in'
      fullPath: '/sign-in'
      preLoaderRoute: typeof SignInRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sign-up': {
      id: '/sign-up'
      path: '/sign-up'
      fullPath: '/sign-up'
      preLoaderRoute: typeof SignUpRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/verify-email': {
      id: '/verify-email'
      path: '/verify-email'
      fullPath: '/verify-email'
      preLoaderRoute: typeof VerifyEmailRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/apps': {
      id: '/_authenticated/apps'
      path: '/apps'
      fullPath: '/apps'
      preLoaderRoute: typeof AuthenticatedAppsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/billing': {
      id: '/_authenticated/billing'
      path: '/billing'
      fullPath: '/billing'
      preLoaderRoute: typeof AuthenticatedBillingRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/onboarding': {
      id: '/_authenticated/onboarding'
      path: '/onboarding'
      fullPath: '/onboarding'
      preLoaderRoute: typeof AuthenticatedOnboardingRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/platform': {
      id: '/_authenticated/platform'
      path: '/platform'
      fullPath: '/platform'
      preLoaderRoute: typeof AuthenticatedPlatformRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/platform-settings': {
      id: '/_authenticated/platform-settings'
      path: '/platform-settings'
      fullPath: '/platform-settings'
      preLoaderRoute: typeof AuthenticatedPlatformSettingsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/settings': {
      id: '/_authenticated/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof AuthenticatedSettingsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/usage': {
      id: '/_authenticated/usage'
      path: '/usage'
      fullPath: '/usage'
      preLoaderRoute: typeof AuthenticatedUsageRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/docs/$slug': {
      id: '/docs/$slug'
      path: '/$slug'
      fullPath: '/docs/$slug'
      preLoaderRoute: typeof DocsSlugRouteImport
      parentRoute: typeof DocsRoute
    }
    '/t/$transferId': {
      id: '/t/$transferId'
      path: '/t/$transferId'
      fullPath: '/t/$transferId'
      preLoaderRoute: typeof TTransferIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/to/$code': {
      id: '/to/$code'
      path: '/to/$code'
      fullPath: '/to/$code'
      preLoaderRoute: typeof ToCodeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/widget/$widgetId': {
      id: '/widget/$widgetId'
      path: '/widget/$widgetId'
      fullPath: '/widget/$widgetId'
      preLoaderRoute: typeof WidgetWidgetIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/app/$applicationId': {
      id: '/_authenticated/app/$applicationId'
      path: '/app/$applicationId'
      fullPath: '/app/$applicationId'
      preLoaderRoute: typeof AuthenticatedAppApplicationIdRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
  }
}

interface AuthenticatedRouteRouteChildren {
  AuthenticatedAppsRoute: typeof AuthenticatedAppsRoute
  AuthenticatedBillingRoute: typeof AuthenticatedBillingRoute
  AuthenticatedOnboardingRoute: typeof AuthenticatedOnboardingRoute
  AuthenticatedPlatformRoute: typeof AuthenticatedPlatformRoute
  AuthenticatedPlatformSettingsRoute: typeof AuthenticatedPlatformSettingsRoute
  AuthenticatedSettingsRoute: typeof AuthenticatedSettingsRoute
  AuthenticatedUsageRoute: typeof AuthenticatedUsageRoute
  AuthenticatedAppApplicationIdRoute: typeof AuthenticatedAppApplicationIdRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedAppsRoute: AuthenticatedAppsRoute,
  AuthenticatedBillingRoute: AuthenticatedBillingRoute,
  AuthenticatedOnboardingRoute: AuthenticatedOnboardingRoute,
  AuthenticatedPlatformRoute: AuthenticatedPlatformRoute,
  AuthenticatedPlatformSettingsRoute: AuthenticatedPlatformSettingsRoute,
  AuthenticatedSettingsRoute: AuthenticatedSettingsRoute,
  AuthenticatedUsageRoute: AuthenticatedUsageRoute,
  AuthenticatedAppApplicationIdRoute: AuthenticatedAppApplicationIdRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

interface DocsRouteChildren {
  DocsSlugRoute: typeof DocsSlugRoute
}

const DocsRouteChildren: DocsRouteChildren = {
  DocsSlugRoute: DocsSlugRoute,
}

const DocsRouteWithChildren = DocsRoute._addFileChildren(DocsRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  AboutRoute: AboutRoute,
  DocsRoute: DocsRouteWithChildren,
  ForgotPasswordRoute: ForgotPasswordRoute,
  HomeRoute: HomeRoute,
  LogoutRoute: LogoutRoute,
  ProductsRoute: ProductsRoute,
  ResetPasswordRoute: ResetPasswordRoute,
  ShareRoute: ShareRoute,
  SignInRoute: SignInRoute,
  SignUpRoute: SignUpRoute,
  VerifyEmailRoute: VerifyEmailRoute,
  TTransferIdRoute: TTransferIdRoute,
  ToCodeRoute: ToCodeRoute,
  WidgetWidgetIdRoute: WidgetWidgetIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
